FROM node:16.18.0-alpine

# Set the working directory to /app inside the container
WORKDIR /app

COPY . ./

RUN npm ci 
RUN npm run build

ENV NODE_ENV production
EXPOSE 3000

CMD [ "npx", "serve", "build" ]
